### ISSUE TITLE
Getting 403 error in GET request

### ISSUE THREAD

**Issue by Vinod-kumar-ios** [robb/URLRequest-AWS#4]
> {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

 [for more detail](https://stackoverflow.com/questions/67077786/aws-authorization-through-header-failed-in-ios)

Please help me in this

**Comment by robb** [comment]
Sorry, I can't help with your implementation but I would suggest following the example step by step, that's how I built this library. https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html
